package com.chanceman.rolls;

import lombok.experimental.UtilityClass;
import net.runelite.api.gameval.ItemID;

import java.util.Set;

@UtilityClass
public class RollItemPools
{
    private static final Set<Integer> TOOL_ITEMS = Set.of(
            ItemID.PESTLE_AND_MORTAR, ItemID.LOBSTER_POT, ItemID.BIG_NET, ItemID.FISHING_ROD,
            ItemID.FLY_FISHING_ROD, ItemID.HARPOON, ItemID.TINDERBOX, ItemID.KNIFE,
            ItemID.SPADE, ItemID.ROPE, ItemID.MACHETTE, ItemID.BRONZE_PICKAXE,
            ItemID.BRONZE_AXE, ItemID.LOCKPICK, ItemID.OILY_FISHING_ROD, ItemID.RING_MOULD,
            ItemID.UNHOLY_SYMBOL_MOULD, ItemID.AMULET_MOULD, ItemID.NECKLACE_MOULD, ItemID.HOLY_SYMBOL_MOULD,
            ItemID.NEEDLE, ItemID.SHEARS, ItemID.CHISEL, ItemID.GLASSBLOWINGPIPE,
            ItemID.BUCKET_EMPTY, ItemID.HAMMER, ItemID.SILVER_SICKLE, ItemID.OIL_LANTERN_UNLIT,
            ItemID.BULLSEYE_LANTERN_LENS, ItemID.SECATEURS, ItemID.RAKE, ItemID.DIBBER,
            ItemID.PLANTPOT_EMPTY, ItemID.PLANTPOT_COMPOST, ItemID.TIARA_MOULD, ItemID.POH_SAW,
            ItemID.XBOWS_SILVER_BOLT_MOULD, ItemID.HUNTING_OJIBWAY_BIRD_SNARE, ItemID.HUNTING_BOX_TRAP, ItemID.HUNTING_BUTTERFLY_NET,
            ItemID.BUTTERFLY_JAR, ItemID.MAGIC_IMP_BOX, ItemID.HUNTING_TEASING_STICK, ItemID.HUNTING_SNARE,
            ItemID.NOOSE_WAND, ItemID.JEWL_BRACELET_MOULD, ItemID.II_MAGIC_BUTTERFLY_NET, ItemID.II_IMPLING_JAR,
            ItemID.BOTTOMLESS_COMPOST_BUCKET, ItemID.BOTTOMLESS_COMPOST_BUCKET_FILLED, ItemID.FISHINGROD_PEARL_OILY
    );

    private static final Set<Integer> QUEST_ITEMS = Set.of(
            ItemID.BUCKET_WAX, ItemID.UNLIT_CANDLE, ItemID.EYE_OF_NEWT, ItemID.RED_SPIDERS_EGGS,
            ItemID.LIMPWURT_ROOT, ItemID.VIAL_WATER, ItemID.VIAL_EMPTY, ItemID.SNAPE_GRASS,
            ItemID.PESTLE_AND_MORTAR, ItemID.UNICORN_HORN_DUST, ItemID.WHITE_BERRIES, ItemID.WINE_OF_ZAMORAK,
            ItemID.JANGERBERRIES, ItemID.GUAM_LEAF, ItemID.MARENTILL, ItemID.HARRALANDER,
            ItemID.KWUARM, ItemID.FISH_FOOD, ItemID.POISON, ItemID.GOBLIN_ARMOUR,
            ItemID.LOBSTER_POT, ItemID.NET, ItemID.BIG_NET, ItemID.FISHING_ROD,
            ItemID.FLY_FISHING_ROD, ItemID.HARPOON, ItemID.FISHING_BAIT, ItemID.FEATHER,
            ItemID.SHRIMP, ItemID.RAW_SARDINE, ItemID.SALMON, ItemID.TROUT,
            ItemID.RAW_COD, ItemID.RAW_MACKEREL, ItemID.RAW_TUNA, ItemID.TUNA,
            ItemID.BASS, ItemID.SWORDFISH, ItemID.RAW_SHARK, ItemID.SHARK,
            ItemID.RAW_MANTARAY, ItemID.RAW_SEATURTLE, ItemID.SEAWEED, ItemID.CLAY,
            ItemID.COPPER_ORE, ItemID.TIN_ORE, ItemID.IRON_ORE, ItemID.MITHRIL_ORE,
            ItemID.COAL, ItemID.BONES, ItemID.BAT_BONES, ItemID.DRAGON_BONES,
            ItemID.FIRERUNE, ItemID.WATERRUNE, ItemID.AIRRUNE, ItemID.EARTHRUNE,
            ItemID.MINDRUNE, ItemID.DEATHRUNE, ItemID.NATURERUNE, ItemID.CHAOSRUNE,
            ItemID.LAWRUNE, ItemID.COSMICRUNE, ItemID.BLOODRUNE, ItemID.SOULRUNE,
            ItemID.STAFFORB, ItemID.TINDERBOX, ItemID.ASHES, ItemID.CADAVABERRIES,
            ItemID.RUNE_THROWNAXE, ItemID.CROSSBOW, ItemID.OAK_LONGBOW, ItemID.WILLOW_LONGBOW,
            ItemID.BLACK_KNIFE, ItemID.KNIFE, ItemID.FUR, ItemID.SILK,
            ItemID.SPADE, ItemID.ROPE, ItemID.GREY_WOLF_FUR, ItemID.WOODPLANK,
            ItemID.PAPYRUS, ItemID.CHARCOAL, ItemID.MACHETTE, ItemID.WHITE_APRON,
            ItemID.PINK_SKIRT, ItemID.LEATHER_GLOVES, ItemID.STEEL_PLATELEGS, ItemID.BLACK_PLATELEGS,
            ItemID.IRON_CHAINBODY, ItemID.STEEL_CHAINBODY, ItemID.ADAMANT_CHAINBODY, ItemID.STEEL_PLATEBODY,
            ItemID.BLACK_PLATEBODY, ItemID.BRONZE_MED_HELM, ItemID.STEEL_MED_HELM, ItemID.STEEL_FULL_HELM,
            ItemID.BLACK_FULL_HELM, ItemID.STEEL_DAGGER, ItemID.BLACK_DAGGER, ItemID.IRON_SPEAR,
            ItemID.STEEL_SPEAR, ItemID.MITHRIL_SPEAR, ItemID.ADAMANT_SPEAR, ItemID.RUNE_SPEAR,
            ItemID.DRAGON_SPEAR, ItemID.BRONZE_PICKAXE, ItemID.ADAMANT_PICKAXE, ItemID.RUNE_PICKAXE,
            ItemID.STEEL_SWORD, ItemID.STEEL_LONGSWORD, ItemID.MITHRIL_2H_SWORD, ItemID.STEEL_WARHAMMER,
            ItemID.BRONZE_AXE, ItemID.MITHRIL_AXE, ItemID.RUNE_AXE, ItemID.PLAINSTAFF,
            ItemID.STEEL_MACE, ItemID.BLANKRUNE, ItemID.AIR_TALISMAN, ItemID.EARTH_TALISMAN,
            ItemID.FIRE_TALISMAN, ItemID.WATER_TALISMAN, ItemID.MIND_TALISMAN, ItemID.DEATH_TALISMAN,
            ItemID.RED_BEAD, ItemID.YELLOW_BEAD, ItemID.BLACK_BEAD, ItemID.WHITE_BEAD,
            ItemID.LOGS, ItemID.MAGIC_LOGS, ItemID.YEW_LOGS, ItemID.MAPLE_LOGS,
            ItemID.WILLOW_LOGS, ItemID.OAK_LOGS, ItemID.LOCKPICK, ItemID.NAILS,
            ItemID.ANTIDRAGONBREATHSHIELD, ItemID.GARLIC, ItemID.SEASONED_SARDINE, ItemID.DOOGLELEAVES,
            ItemID.RING_MOULD, ItemID.NECKLACE_MOULD, ItemID.DIAMOND, ItemID.RUBY,
            ItemID.EMERALD, ItemID.SAPPHIRE, ItemID.OPAL, ItemID.JADE,
            ItemID.RED_TOPAZ, ItemID.DRAGONSTONE, ItemID.STRUNG_SAPPHIRE_AMULET, ItemID.BLESSEDSTAR,
            ItemID.NEEDLE, ItemID.THREAD, ItemID.SHEARS, ItemID.WOOL,
            ItemID.LEATHER, ItemID.HARD_LEATHER, ItemID.CHISEL, ItemID.BROWN_APRON,
            ItemID.BALL_OF_WOOL, ItemID.SOFTCLAY, ItemID.REDDYE, ItemID.YELLOWDYE,
            ItemID.BLUEDYE, ItemID.ORANGEDYE, ItemID.GREENDYE, ItemID.PURPLEDYE,
            ItemID.MOLTEN_GLASS, ItemID.BOW_STRING, ItemID.BUCKET_SAND, ItemID.GLASSBLOWINGPIPE,
            ItemID.BOWL_UNFIRED, ItemID.BRONZECRAFTWIRE, ItemID.DESERT_SHIRT, ItemID.DESERT_ROBE,
            ItemID.DESERT_BOOTS, ItemID.SHANTAY_PASS, ItemID.CAKE_TIN, ItemID.CAKE,
            ItemID.CHOCOLATE_CAKE, ItemID.ASGARNIAN_ALE, ItemID.WIZARDS_MIND_BOMB, ItemID.GREENMANS_ALE,
            ItemID.DWARVEN_STOUT, ItemID.BEER, ItemID.BEER_GLASS, ItemID.BOWL_WATER,
            ItemID.BOWL_EMPTY, ItemID.BUCKET_EMPTY, ItemID.BUCKET_MILK, ItemID.BUCKET_WATER,
            ItemID.POT_EMPTY, ItemID.POT_FLOUR, ItemID.JUG_WATER, ItemID.SWAMP_TAR,
            ItemID.SWAMPPASTE, ItemID.POTATO, ItemID.EGG, ItemID.GRAIN,
            ItemID.REDBERRIES, ItemID.ONION, ItemID.BANANA, ItemID.CABBAGE,
            ItemID.KEBAB, ItemID.CHOCOLATE_BAR, ItemID.CHOCOLATE_DUST, ItemID.CUP_OF_TEA,
            ItemID.TOMATO, ItemID.CHEESE, ItemID.GRAPES, ItemID.STEW,
            ItemID.SPICESPOT, ItemID.VODKA, ItemID.PREMADE_FRUIT_BLAST, ItemID.FRUIT_BLAST,
            ItemID.LEMON, ItemID.ORANGE, ItemID.ORANGE_SLICES, ItemID.PINEAPPLE_CHUNKS,
            ItemID.DWELLBERRIES, ItemID.EQUA_LEAVES, ItemID.POT_OF_CREAM, ItemID.RAW_BEEF,
            ItemID.RAW_RAT_MEAT, ItemID.RAW_BEAR_MEAT, ItemID.RAW_CHICKEN, ItemID.COOKED_MEAT,
            ItemID.GNOME_SPICE, ItemID.TOAD_CRUNCHIES, ItemID.PREMADE_TOAD_CRUNCHIES, ItemID.BREAD,
            ItemID.REDBERRY_PIE, ItemID.HAMMER, ItemID.BRONZE_BAR, ItemID.IRON_BAR,
            ItemID.STEEL_BAR, ItemID.SILVER_BAR, ItemID.GOLD_BAR, ItemID.MITHRIL_BAR,
            ItemID.RUNITE_BAR, ItemID.RING_OF_LIFE, ItemID.WOLF_BONES, ItemID.RAW_CHOMPY,
            ItemID.SILVER_SICKLE, ItemID.MORTMYREMUSHROOM, ItemID.MORTMYREBUDDINGSTEM, ItemID.MORTMYREPEAR,
            ItemID.DEATH_CLIMBINGBOOTS, ItemID.DEATH_SPIKEDBOOTS, ItemID.TBWT_JOGRE_BONES, ItemID.TBWT_SLICED_BANANA,
            ItemID.MM_NORMAL_MONKEY_BONES, ItemID.LIMESTONE, ItemID.COOKED_RABBIT, ItemID.MORT_SLIMEY_EEL,
            ItemID.LIMESTONEBRICK, ItemID.FLAMTAER_HAMMER, ItemID.VIKING_TANKARD_FULL, ItemID.MM_MONKEY_NUTS,
            ItemID.SLAYER_MIRROR_SHIELD, ItemID.SLAYER_BAG_OF_SALT, ItemID.SLAYER_FACEMASK, ItemID.FAVOUR_AIRTIGHT_POT,
            ItemID.POTLID, ItemID.CUP_HOT_WATER, ItemID.BULLSEYE_LANTERN_LENS, ItemID.BULLSEYE_LANTERN_UNLIT,
            ItemID.FEUD_KARIDIAN_TURBAN, ItemID.FEUD_KARIDIAN_FAKEBEARD, ItemID.FD_CRUSHED_GARLIC, ItemID.ICS_LITTLE_LINEN,
            ItemID.ICS_LITTLE_SAP_BUCKET, ItemID.MISTRUNE, ItemID.MUDRUNE, ItemID.LAVARUNE,
            ItemID.ZOGRE_BOW, ItemID.MARIGOLD_SEED, ItemID.SNAPDRAGON_SEED, ItemID.CADANTINE_SEED,
            ItemID.POTATO_SEED, ItemID.ONION_SEED, ItemID.CABBAGE_SEED, ItemID.GARDENING_TROWEL,
            ItemID.SECATEURS, ItemID.WATERING_CAN_0, ItemID.RAKE, ItemID.DIBBER,
            ItemID.PLANTPOT_COMPOST, ItemID.SACK_EMPTY, ItemID.ELEMENTAL_TALISMAN, ItemID.TIARA,
            ItemID.TIARA_MIND, ItemID.TIARA_DEATH, ItemID.ALE_YEAST, ItemID.WILLOW_BRANCH,
            ItemID.SWEETCORN, ItemID.BARLEY_MALT, ItemID.BUCKET_COMPOST, ItemID.BUCKET_SUPERCOMPOST,
            ItemID.PLANT_CURE, ItemID.POTATO_BAKED, ItemID.DRAGON_AXE, ItemID.AGRITH_DESERT_SHIRT_DYED,
            ItemID.AGRITH_DESERT_ROBE_DYED, ItemID.WEREWOLVE_FUR, ItemID.BOWL_SWEETCORN, ItemID.SLAYER_BOOTS,
            ItemID.SPIT_IRON, ItemID.CHICKENQUEST_POT_CORNFLOUR, ItemID.BLANKRUNE_HIGH, ItemID.POH_TABLET_VARROCKTELEPORT,
            ItemID.POH_TABLET_ENCHANTEMERALD, ItemID.POH_FLATPACK_BEERBARREL3, ItemID.POH_FLATPACK_BEERBARREL4, ItemID.PLANK_OAK,
            ItemID.PLANK_MAHOGANY, ItemID.CLOTH, ItemID.POH_CLOCKWORK_MECHANISM, ItemID.POH_SAW,
            ItemID.ASTRALRUNE, ItemID.XBOWS_GRAPPLE_TIP_BOLT_MITHRIL, ItemID.XBOWS_GRAPPLE_TIP_BOLT_MITHRIL_ROPE, ItemID.HUNTING_BOX_TRAP,
            ItemID.ANMA_P_BUTTONS, ItemID.ARCTIC_PINE_SPLIT, ItemID.YAK_HIDE_ARMOUR_BODY, ItemID.YAK_HIDE_ARMOUR_GREAVES,
            ItemID.FREMMENIK_ROUND_SHIELD, ItemID.BRAIN_INV_WOODEN_CAT, ItemID.BRUT_ROE, ItemID.TELEPORTSCROLL_CERBERUS,
            ItemID.DRAGON_WARHAMMER, ItemID.VAMPYRE_RING, ItemID.BUCKET_ULTRACOMPOST, ItemID.CATALYTIC_TALISMAN,
            ItemID.TIARA_CATALYTIC, ItemID.POH_TABLET_FORTISTELEPORT, ItemID.HUNTING_JERBOA_TAIL
    );

    public static boolean isToolItem(int itemId)
    {
        return TOOL_ITEMS.contains(itemId);
    }

    public static boolean isQuestItem(int itemId)
    {
        return QUEST_ITEMS.contains(itemId) && !TOOL_ITEMS.contains(itemId);
    }

}
